// AUTO-GENERATED by python/build_vessels_topology.py -- DO NOT EDIT BY HAND.
// Arterial/venous vascular-tree topology (SVG pixel coords, y-down).
#ifndef QUAD_JUNCTIONS_VESSELS_TREE_DATA_HPP
#define QUAD_JUNCTIONS_VESSELS_TREE_DATA_HPP
namespace quad_junctions {
namespace vessels_data {

struct VJunc { int id; double x, y; int parent; int gen; };
// Connector: arterial junction + arterial leaf endpoint, venous junction + endpoint, is_lens.
struct VConn { int a_jct; double ax, ay; int v_jct; double vx, vy; int is_lens; };

static const int n_junc = 20;
static const VJunc juncs[n_junc] = {
  {  0,   80.0,  270.0,  -1, 0 },  // J1
  {  1,  132.0,  160.0,   0, 1 },  // J2
  {  2,  132.0,  380.0,   0, 1 },  // J3
  {  3,  178.0,  100.0,   1, 2 },  // J4
  {  4,  178.0,  220.0,   1, 2 },  // J5
  {  5,  178.0,  320.0,   2, 2 },  // J6
  {  6,  178.0,  440.0,   2, 2 },  // J7
  {  7,  223.0,  130.0,   3, 3 },  // Jsub1
  {  8,  223.0,  350.0,   5, 3 },  // Jsub2
  {  9,  273.0,  470.0,   6, 3 },  // Jsub3
  { 10,  625.0,  270.0,  -1, 0 },  // VJ1
  { 11,  575.0,  160.0,  10, 1 },  // VJ2
  { 12,  575.0,  380.0,  10, 1 },  // VJ3
  { 13,  527.0,  100.0,  11, 2 },  // VJ4
  { 14,  527.0,  220.0,  11, 2 },  // VJ5
  { 15,  527.0,  320.0,  12, 2 },  // VJ6
  { 16,  527.0,  440.0,  12, 2 },  // VJ7
  { 17,  490.0,  130.0,  13, 3 },  // VJsub1
  { 18,  490.0,  350.0,  15, 3 },  // VJsub2
  { 19,  490.0,  470.0,  16, 3 },  // VJsub3
};

static const int n_conn = 11;
static const VConn conns[n_conn] = {
  {  3,  205.0,   70.0, 13,  490.0,   70.0, 0 },  // 0: A0<->V0
  {  7,  250.0,  110.0, 17,  455.0,  110.0, 1 },  // 1: A1<->V1
  {  7,  250.0,  150.0, 17,  455.0,  150.0, 1 },  // 2: A2<->V2
  {  4,  205.0,  190.0, 14,  490.0,  190.0, 1 },  // 3: A3<->V3
  {  4,  205.0,  250.0, 14,  490.0,  250.0, 1 },  // 4: A4<->V4
  {  5,  205.0,  290.0, 15,  490.0,  290.0, 0 },  // 5: A5<->V5
  {  8,  250.0,  330.0, 18,  455.0,  330.0, 1 },  // 6: A6<->V6
  {  8,  250.0,  370.0, 18,  455.0,  370.0, 1 },  // 7: A7<->V7
  {  6,  205.0,  410.0, 16,  490.0,  410.0, 0 },  // 8: A8<->V8
  {  9,  300.0,  450.0, 19,  455.0,  450.0, 1 },  // 9: A9<->V9
  {  9,  300.0,  490.0, 19,  455.0,  490.0, 1 },  // 10: A10<->V10
};

}  // namespace vessels_data
}  // namespace quad_junctions
#endif
